### ISSUE TITLE
Could not find gem 'database_cleaner-active_record' in any of the gem sources listed in your Gemfile or available on this machine.

### ISSUE THREAD

**Issue by krtschmr** [DatabaseCleaner/database_cleaner-active_record#1]
group :test do
      gem 'database_cleaner-active_record'
    end

from the docs

**Comment by JonRowe** [comment]
I don't think this was ever released, see https://github.com/DatabaseCleaner/database_cleaner for now.

**Comment by etagwerker** [comment]
@krtschmr @JonRowe This project is WIP (version 2.0). 

For now use https://rubygems.org/gems/database_cleaner

**Comment by borenho** [comment]
Getting the same in 2019. Why is it still in the docs of this was never released?

**Comment by JonRowe** [comment]
Its the docs for the master unreleased branch, thats all

**Comment by borenho** [comment]
Could we edit it? It's quite confusing for sure. Since it's in the official docs that everyone sees

**Comment by JonRowe** [comment]
Its not the official docs for the released version... I'd support a note in the readme restating that with a link to the current version readme, I'm not the maintainer of the project however, @etagwerker does that seem reasonable?

**Comment by etagwerker** [comment]
@borenho You can find the documentation for v1.7.0 over here: https://github.com/DatabaseCleaner/database_cleaner/tree/v1.7.0

@JonRowe @borenho I think it is reasonable to add a note to the README in `master` so people who find that page are not confused. If one of you could submit a PR that would be very much appreciated. 👍

**Comment by borenho** [comment]
@JonRowe , @etagwerker , let me go for this one

**Comment by borenho** [comment]
@etagwerker @JonRowe find the pull request for this here https://github.com/DatabaseCleaner/database_cleaner/pull/589

**Comment by botandrose** [comment]
@etagwerker @JonRowe I believe this is ready for release, and has been for a while. We could sidestep all these issues simply by releasing v1.8.0, IMO.

**Comment by etagwerker** [comment]
@botandrose I agree, I'll work on a release later this week.

**Comment by 645383** [comment]
Readme is very useful!

**Comment by botandrose** [comment]
@etagwerker I offer my assistance in making the v1.8.0 releases, and general maintenance of the database_cleaner family of gems, if you'd like to delegate.

**Comment by hron84** [comment]
@etagwerker @JonRowe 

Since the release seems like definitely delayed, could you please roll back the old `README` on the master branch of https://github.com/DatabaseCleaner/database_cleaner? The current `README` points (partially) to this gem and since it is not released yet, misleads newcomers or others who want to see correct documentation. I absolute understand that your life stuff is happened and you do not have time for a release, I just asking to take care at least to the documentation to not have incorrect information. 

This issue is also reported on DatabaseCleaner/database_cleaner#587

**Comment by JonRowe** [comment]
The readme explicitly mentions that it is for a unreleased version, and links to the currently released read me, as per DatabaseCleaner/database_cleaner#589
