### ISSUE TITLE
Monkeypatching ActiveRecord code is excessive!

### ISSUE THREAD

**Issue by botandrose** [DatabaseCleaner/database_cleaner-active_record#33]
I want to see if we can refactor to do what we need to do without modifying AR in place.

**Comment by etagwerker** [comment]
@botandrose That sounds like a good idea. Any monkey patches that we could start with?

**Comment by ryanong** [comment]
Where does it modify AR? I just did a quick skim and nothing does

**Comment by botandrose** [comment]
Yeah 4a282e289470a91323f4fbfc1444ecb2ed0bd3be was a big step forward, here. Moving from monkeypatching AR internals, to wrapping them in a decorator. I think we can close this now.
