### ISSUE TITLE
Rails 6 with database_cleaner-active_record ~>1.8 wipe all tables even with except

### ISSUE THREAD

**Issue by bf39l** [DatabaseCleaner/database_cleaner-active_record#44]
database: postgresql 11
Rails 6
rspc-rails ~>4.0
database_cleaner-active_record ~>1.8 
spec_helper.rb
```
  require 'database_cleaner-active_record'
  DatabaseCleaner[:active_record, connection: :test]

  tables_to_be_excluded = %w[public.spatial_ref_sys public.foo]

  config.before(:suite) do
    load "#{Rails.root}/db/seeds.rb"
    DatabaseCleaner.strategy = :truncation, { except: tables_to_be_excluded }
    DatabaseCleaner.clean_with(:truncation, { except: tables_to_be_excluded })
    puts 'Cleaned up database and feed seeds'
    # this step will wipe all data in all tables
  end
  config.before(:each) do
    DatabaseCleaner.start
  end
  config.after(:each) do
    DatabaseCleaner.clean
  end
```

**Comment by bf39l** [comment]
I updated gem to database_cleaner, = 1.7.0 with following rspec config
```
  config.before(:suite) do
    DatabaseCleaner.strategy = :truncation, { except: tables_to_be_excluded }
    DatabaseCleaner.clean_with(:truncation, { except: tables_to_be_excluded })
    load "#{Rails.root}/db/seeds.rb"
  end

  config.before(:each) do
    DatabaseCleaner.strategy = :truncation, { except: tables_to_be_excluded }
    DatabaseCleaner.clean_with(:truncation, { except: tables_to_be_excluded })
  end
```
And confirmed database_cleaner just clean up required tables.

**Comment by bsuchodolski** [comment]
I've just spent an afternoon to debug similar problem and I've found out that if you are using postgres then tables are truncated with CASCADE option which truncates not only tables that are not in `except` option but if any of this table references table that is truncated, it will be silently truncated as well despite being in `except`.

**Comment by bf39l** [comment]
Right, that kinda make sence, just wondering if I have two tables like below
Table "students": id (pk), name
Table "classrooms": id (pk), student_id (fk =>id from students)
When I clean tuples in classrooms, will it clean up students?

**Comment by bf39l** [comment]
Understood now. I will close this issue now and head back to that project to give a try. Thank you @bsuchodolski .
