### ISSUE TITLE
Versions before 1.8.0?

### ISSUE THREAD

**Issue by joelmichael** [DatabaseCleaner/database_cleaner-active_record#45]
I am working on an older app and I want to install version 1.7.0 to avoid the deprecation warning related to `DatabaseCleaner.connections` which is introduced in 1.8.0. A gem we use, `cucumber-rails` is on an older version which triggers this warning, and upgrading won't be simple (requires upgrading Ruby).

My question is, why are versions of database_cleaner-active_record before 1.8.0 no longer available on Rubygems? Thanks.

**Comment by etagwerker** [comment]
@joelmichael if you want to use that version you need to use database_cleaner, not database_cleaner-active_record.
