### ISSUE TITLE
Strategy :transaction doesn't work with click_button

### ISSUE THREAD

**Issue by skydev2020** [DatabaseCleaner/database_cleaner-active_record#53]
This is very obvious error I think.
I have this code.

```
describe "the signin process", type: :feature do

  it "signs me in" do
    @admin_user = FactoryBot.create(:admin_user)
    
    visit '/users/sign_in'
    within("#form-login") do
      fill_in 'user_email', with: @admin_user.email
      fill_in 'user_password', with: @admin_user.password
    end
    click_button 'Sign in'
    users = User.all()    
    puts users[3] #Debug message to confirm new user is added to db
    expect(page).to have_content 'Welcome'
    
  end

end
```

And this is the active_database_cleaner configration

```
RSpec.configure do |config|
 config.use_transactional_fixtures = false

  config.before(:suite) do
    # DatabaseCleaner.clean_with(:truncation)    
  end

  config.before(:each) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.start #if I comment this line it works
  end
  
  config.append_after(:each) do
    DatabaseCleaner.clean
  end
end
```

But click_button doesn't login and it remains or redirected back to login form
if I change the :transaction to :truncation it works.
any idea?

**Comment by botandrose** [comment]
Hi @skydev2020, can you reduce this down to a failing test that you can share in a repo somewhere that I can clone and poke around?

**Comment by skydev2020** [comment]
@botandrose do you need running app?

**Comment by botandrose** [comment]
@skydev2020 Yeah, just some repo with a failing test that I can clone and see the error

**Comment by skydev2020** [comment]
I tried to customize existing project but since it is big/private project couldn't do it.
but this error is very obvious...

**Comment by botandrose** [comment]
It is not obvious to me, unfortunately. Feel free to post a repo
demonstrating the issue, or a PR to fix it, but if I can't reproduce the
error I can't fix it.

**Comment by skydev2020** [comment]
ok. I will prepare it and upload

**Comment by skydev2020** [comment]
@botandrose I invited you to the project.
I run this command to test
bundle exec rspec -b spec/features/sign_in_spec.rb 
And I left comment in spec/support/database_cleaner.rb line no. #11.
Thanks

**Comment by botandrose** [comment]
Thank you! I'll take a look now

**Comment by botandrose** [comment]
@skydev2020 Ah, okay, I see the problem. The problem is that the test and the rails app are using different database connections, so the user database entry created within a transaction in the test is not visible to the database connection in the app. This part of the README describes your situation exactly: https://github.com/DatabaseCleaner/database_cleaner#rspec-with-capybara-example

If you want to pursue it on your own, I know there are ways to force the test and the app to share the same database connection, but it seems to be a bit of a hack, and isn't supported by database_cleaner at this time. In the meantime, just use the truncation strategy.

**Comment by skydev2020** [comment]
@botandrose thanks for your reply.
you mean if we are using a driver other than rack_test, "transaction" strategy will not work?

**Comment by botandrose** [comment]
Correct. In other drivers, the test and the app are using different
database connections, and so they don't share transactions.

**Comment by skydev2020** [comment]
Thanks for answer.
I will use different strategy.
