### ISSUE TITLE
Broken with Rails 7.1

### ISSUE THREAD

**Issue by mathieujobin** [DatabaseCleaner/database_cleaner-active_record#81]
I am testing upgrading my app with rails main branch (7.1-alpha)
and I am getting an error with this gem

https://github.com/DatabaseCleaner/database_cleaner-active_record/blob/654de96ba02807baa13c3873804a189ffd8e4f08/lib/database_cleaner/active_record/base.rb#L18

![image](https://user-images.githubusercontent.com/99191/214521772-2eddc774-9773-496a-8cb0-c63c97559ebb.png)

**Comment by mathieujobin** [comment]
I have a WIP branch for this, appears to be working.

https://github.com/DatabaseCleaner/database_cleaner-active_record/compare/main...mathieujobin:database_cleaner-active_record:support-rails-7.1

CC: @wollistik

**Comment by etagwerker** [comment]
Closed by #78
