### ISSUE TITLE
v2.0.1 is throwing deprecation warning for using #tables instead of #data_sources

### ISSUE THREAD

**Issue by EduardoRSeifert** [DatabaseCleaner/database_cleaner-active_record#84]
```DEPRECATION WARNING: #tables currently returns both tables and views. This behavior is deprecated and will be changed with Rails 5.1 to only return tables. Use #data_sources instead. ```

This is being thrown when i run `DatabaseCleaner.clean_with(:truncation)`

After some searching, i found 2 PRs that fixed this and were merged onto master, [PR1](https://github.com/DatabaseCleaner/database_cleaner/pull/415)  [PR2](https://github.com/DatabaseCleaner/database_cleaner/pull/574), but it seems like these fixes got lost somewhere.

I used git bisect to find which commit broke and it may have been this one, b83ed7d1e39c16ccd54342f37f4d1094366bc579 , but i do admit that i narrowed my search to what commit broke it on the database_cleaner gem, not on database_cleaner-active_record gem, so i am not sure

**Comment by etagwerker** [comment]
I believe this is now fixed on https://github.com/DatabaseCleaner/database_cleaner-active_record/blob/main/CHANGELOG.md#v210-2023-02-17
