### ISSUE TITLE
Exclude SQLite views from tables_to_truncate

### ISSUE THREAD

**Issue by antoniodejesusochoasolano** [DatabaseCleaner/database_cleaner-active_record#9]
With SQLite3, DatabaseCleaner tries to truncate views.

```
initialize`: SQLite3::SQLException: cannot modify <table> because it is a view: DELETE FROM <table>
```

Issue appears to be [here](https://github.com/DatabaseCleaner/database_cleaner/blob/9755bc55dcb2b2f17df15e4d8fe94772487c2404/lib/database_cleaner/active_record/truncation.rb#L25).

```ruby
def database_cleaner_view_cache
  @views ||= select_values("select table_name from information_schema.views where table_schema = '#{current_database}'") rescue []
end
```
Running `select table_name from information_schema.views` in SQLite3 returns

```
no such table: information_schema.views: select table_name from information_schema.views
```

Looks like this was fixed for other adapters [here](https://github.com/DatabaseCleaner/database_cleaner/pull/29).

**Comment by botandrose** [comment]
Should be fixed by #4. Reopen if not!
